### ISSUE TITLE
Exporting model after training

### ISSUE THREAD

**Issue by kabage** [SimoneAlbertini/BarcodeDetectionHough#1]
How do i export a model i can then use for barcode detection on arbitrary images?

**Comment by SimoneAlbertini** [comment]
Hello.

What do you exactly mean by exporting the model?
If you mean the neural network, the code actually uses an already trained MLP network: it just loads it and employ it for generalization.
There is a ".net" file in the codebase with the weight matrix of such network.

Anyway, the whole program is actually a pileline made of several phases (explained in the paper) and it is meant to reproduce the results presented in the paper.

I hope I have answered your question and thank you for using my code.
